# Generated by Django 3.1.3 on 2020-12-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblist',
            old_name='i_date',
            new_name='date',
        ),
    ]
